Login
BarackOLlama/Festispec-App pull request #49
Opened 2018-11-19 11:02 UTC by gharamorth

2018-11-19 15:12 UTC, Evert-Arends commented on FSBeheer/FSBeheer/FSContext.cs
> +        internal object temp;
Delete?

2018-11-19 15:12 UTC, Evert-Arends commented on FSBeheer/FSBeheer/ViewModel/AccountVM.cs
> +    public class AccountVM : ViewModelBase
Do not

2018-11-19 15:12 UTC, Evert-Arends commented on FSBeheer/FSBeheer/ViewModel/CreateQuestionViewModel.cs
> +            using (var context = new CustomFSContext())
Please use the correct classes for this functionality as stated in the CustomFXContext

2018-11-19 15:12 UTC, Evert-Arends commented on FSBeheer/FSBeheer/ViewModel/CreateQuestionViewModel.cs
> +        public void AddQuestion()
What?

2018-11-19 15:12 UTC, Evert-Arends commented on FSBeheer/FSBeheer/ViewModel/LoginViewModel.cs
> +            int i = 5;
Please remove

2018-11-19 15:33 UTC, gharamorth commented on FSBeheer/FSBeheer/ViewModel/CreateQuestionViewModel.cs
> +        public void AddQuestion()
What

2018-11-20 16:26 UTC, Evert-Arends requested changes

2018-11-20 16:26 UTC, Evert-Arends commented on FSBeheer/FSBeheer/VM/QuestionnaireVM.cs
> +namespace FSBeheer.ViewModel
Wrong namespace? This should be in the VM folder? Please explain a bit further?

2018-11-20 18:11 UTC, gharamorth commented on FSBeheer/FSBeheer/VM/QuestionnaireVM.cs
> +namespace FSBeheer.ViewModel
Wrong namespace yeah, it is in the VM folder

2018-11-20 19:21 UTC, Evert-Arends commented
Even development pullen en pushen, dan merge ik m

2018-11-21 10:22 UTC, Evert-Arends requested changes

2018-11-21 10:22 UTC, Evert-Arends commented on FSBeheer/FSBeheer/ViewModel/QuestionnairesViewModel.cs
> +        public ICommand ViewQuestionnaireCommand { get; set; }
ICommand should not be used, use RelayCommand instad.

2018-11-21 10:30 UTC, Evert-Arends requested changes

2018-11-21 10:30 UTC, Evert-Arends commented on FSBeheer/FSBeheer/FSContext.cs
> +        internal object temp;
@gharamorth Is dit opgelost?

2018-11-21 10:32 UTC, Evert-Arends approved these changes

2018-11-21 10:32 UTC, merged