Global validation
BarackOLlama/Festispec-App pull request #76
Opened 2018-12-31 09:23 UTC by gharamorth

Denk nog niet klaar te zijn maar er zitten hier al wel belangrijke functionaliteiten in die handig kunnen zijn op development.
--edit
Validatie is verder uitgebreid. Er wordt gekeken of postcodes, e-mail adressen, etc. valide zijn middels regex. In principe is iedere property verplicht. Uitzonderingen zijn dingen zoals dat een inspecteur niet per se een inspectie moet hebben.
TODO: validatie van properties alfabetisch ordenen.

2018-12-31 15:52 UTC, Evert-Arends commented
@bartkoevoets This one is for you

2018-12-31 15:52 UTC, Evert-Arends commented
@gharamorth Pull & push

2018-12-31 18:38 UTC, gharamorth commented
@Evert-Arends done.

2019-01-01 22:02 UTC, bartkoevoets requested changes
- Please implement BaseView in EditQuestionView.xaml and EditQuestionView.xaml.cs (don't forget to edit Name to x:Name)
- In CreateEditContactViewModel.cs, please specify the problem when giving the user an error message
- Fix the article (lidwoord) on line 114 in CreateEditContactViewModel.cs

2019-01-02 19:02 UTC, bartkoevoets approved these changes
Seems good, approved

2019-01-03 16:11 UTC, merged